update=13.08.2017 20:12:57
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=../../KiCad Libraries/User
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=D:/Soft/KiCad Libraries/kicad-library/library/ftdi
LibName31=D:/Soft/KiCad Libraries/kicad-library/library/74xgxx
LibName32=D:/Soft/KiCad Libraries/kicad-library/library/74xx
LibName33=D:/Soft/KiCad Libraries/kicad-library/library/ac-dc
LibName34=D:/Soft/KiCad Libraries/kicad-library/library/actel
LibName35=D:/Soft/KiCad Libraries/kicad-library/library/adc-dac
LibName36=D:/Soft/KiCad Libraries/kicad-library/library/allegro
LibName37=D:/Soft/KiCad Libraries/kicad-library/library/Altera
LibName38=D:/Soft/KiCad Libraries/kicad-library/library/analog_devices
LibName39=D:/Soft/KiCad Libraries/kicad-library/library/analog_switches
LibName40=D:/Soft/KiCad Libraries/kicad-library/library/atmel
LibName41=D:/Soft/KiCad Libraries/kicad-library/library/audio
LibName42=D:/Soft/KiCad Libraries/kicad-library/library/battery_management
LibName43=D:/Soft/KiCad Libraries/kicad-library/library/bbd
LibName44=D:/Soft/KiCad Libraries/kicad-library/library/bosch
LibName45=D:/Soft/KiCad Libraries/kicad-library/library/brooktre
LibName46=D:/Soft/KiCad Libraries/kicad-library/library/cmos_ieee
LibName47=D:/Soft/KiCad Libraries/kicad-library/library/cmos4000
LibName48=D:/Soft/KiCad Libraries/kicad-library/library/conn
LibName49=D:/Soft/KiCad Libraries/kicad-library/library/contrib
LibName50=D:/Soft/KiCad Libraries/kicad-library/library/cypress
LibName51=D:/Soft/KiCad Libraries/kicad-library/library/dc-dc
LibName52=D:/Soft/KiCad Libraries/kicad-library/library/device
LibName53=D:/Soft/KiCad Libraries/kicad-library/library/digital-audio
LibName54=D:/Soft/KiCad Libraries/kicad-library/library/diode
LibName55=D:/Soft/KiCad Libraries/kicad-library/library/display
LibName56=D:/Soft/KiCad Libraries/kicad-library/library/dsp
LibName57=D:/Soft/KiCad Libraries/kicad-library/library/elec-unifil
LibName58=D:/Soft/KiCad Libraries/kicad-library/library/ESD_Protection
LibName59=D:/Soft/KiCad Libraries/kicad-library/library/gennum
LibName60=D:/Soft/KiCad Libraries/kicad-library/library/graphic_symbols
LibName61=D:/Soft/KiCad Libraries/kicad-library/library/hc11
LibName62=D:/Soft/KiCad Libraries/kicad-library/library/infineon
LibName63=D:/Soft/KiCad Libraries/kicad-library/library/intel
LibName64=D:/Soft/KiCad Libraries/kicad-library/library/interface
LibName65=D:/Soft/KiCad Libraries/kicad-library/library/intersil
LibName66=D:/Soft/KiCad Libraries/kicad-library/library/ir
LibName67=D:/Soft/KiCad Libraries/kicad-library/library/Lattice
LibName68=D:/Soft/KiCad Libraries/kicad-library/library/leds
LibName69=D:/Soft/KiCad Libraries/kicad-library/library/LEM
LibName70=D:/Soft/KiCad Libraries/kicad-library/library/linear
LibName71=D:/Soft/KiCad Libraries/kicad-library/library/maxim
LibName72=D:/Soft/KiCad Libraries/kicad-library/library/mechanical
LibName73=D:/Soft/KiCad Libraries/kicad-library/library/memory
LibName74=D:/Soft/KiCad Libraries/kicad-library/library/microchip
LibName75=D:/Soft/KiCad Libraries/kicad-library/library/microchip_dspic33dsc
LibName76=D:/Soft/KiCad Libraries/kicad-library/library/microchip_pic10mcu
LibName77=D:/Soft/KiCad Libraries/kicad-library/library/microchip_pic12mcu
LibName78=D:/Soft/KiCad Libraries/kicad-library/library/microchip_pic16mcu
LibName79=D:/Soft/KiCad Libraries/kicad-library/library/microchip_pic18mcu
LibName80=D:/Soft/KiCad Libraries/kicad-library/library/microchip_pic24mcu
LibName81=D:/Soft/KiCad Libraries/kicad-library/library/microchip_pic32mcu
LibName82=D:/Soft/KiCad Libraries/kicad-library/library/microcontrollers
LibName83=D:/Soft/KiCad Libraries/kicad-library/library/modules
LibName84=D:/Soft/KiCad Libraries/kicad-library/library/motor_drivers
LibName85=D:/Soft/KiCad Libraries/kicad-library/library/motorola
LibName86=D:/Soft/KiCad Libraries/kicad-library/library/motors
LibName87=D:/Soft/KiCad Libraries/kicad-library/library/msp430
LibName88=D:/Soft/KiCad Libraries/kicad-library/library/nordicsemi
LibName89=D:/Soft/KiCad Libraries/kicad-library/library/nxp
LibName90=D:/Soft/KiCad Libraries/kicad-library/library/nxp_armmcu
LibName91=D:/Soft/KiCad Libraries/kicad-library/library/onsemi
LibName92=D:/Soft/KiCad Libraries/kicad-library/library/opto
LibName93=D:/Soft/KiCad Libraries/kicad-library/library/Oscillators
LibName94=D:/Soft/KiCad Libraries/kicad-library/library/philips
LibName95=D:/Soft/KiCad Libraries/kicad-library/library/power
LibName96=D:/Soft/KiCad Libraries/kicad-library/library/Power_Management
LibName97=D:/Soft/KiCad Libraries/kicad-library/library/powerint
LibName98=D:/Soft/KiCad Libraries/kicad-library/library/pspice
LibName99=D:/Soft/KiCad Libraries/kicad-library/library/references
LibName100=D:/Soft/KiCad Libraries/kicad-library/library/regul
LibName101=D:/Soft/KiCad Libraries/kicad-library/library/relays
LibName102=D:/Soft/KiCad Libraries/kicad-library/library/rfcom
LibName103=D:/Soft/KiCad Libraries/kicad-library/library/RFSolutions
LibName104=D:/Soft/KiCad Libraries/kicad-library/library/sensors
LibName105=D:/Soft/KiCad Libraries/kicad-library/library/silabs
LibName106=D:/Soft/KiCad Libraries/kicad-library/library/siliconi
LibName107=D:/Soft/KiCad Libraries/kicad-library/library/stm8
LibName108=D:/Soft/KiCad Libraries/kicad-library/library/stm32
LibName109=D:/Soft/KiCad Libraries/kicad-library/library/supertex
LibName110=D:/Soft/KiCad Libraries/kicad-library/library/switches
LibName111=D:/Soft/KiCad Libraries/kicad-library/library/texas
LibName112=D:/Soft/KiCad Libraries/kicad-library/library/transf
LibName113=D:/Soft/KiCad Libraries/kicad-library/library/transistors
LibName114=D:/Soft/KiCad Libraries/kicad-library/library/triac_thyristor
LibName115=D:/Soft/KiCad Libraries/kicad-library/library/ttl_ieee
LibName116=D:/Soft/KiCad Libraries/kicad-library/library/valves
LibName117=D:/Soft/KiCad Libraries/kicad-library/library/video
LibName118=D:/Soft/KiCad Libraries/kicad-library/library/wiznet
LibName119=D:/Soft/KiCad Libraries/kicad-library/library/Worldsemi
LibName120=D:/Soft/KiCad Libraries/kicad-library/library/Xicor
LibName121=D:/Soft/KiCad Libraries/kicad-library/library/xilinx
LibName122=D:/Soft/KiCad Libraries/kicad-library/library/zetex
LibName123=D:/Soft/KiCad Libraries/kicad-library/library/Zilog
